name: Build Static Executable with MinGW

on: [push]

jobs:
  build-static-exe:
    runs-on: windows-latest
    steps:
      - name: Install Chocolatey
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install MinGW-w64
        shell: pwsh
        run: choco install mingw -y

      - name: Verify Installation
        shell: pwsh
        run: gcc --version

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List Installed Libraries
        shell: pwsh
        run: dir C:\tools\mingw64\x86_64-w64-mingw32\lib

      - name: Compile Static Executable
        shell: pwsh
        run: |
          echo '#include <stdio.h>' > hello.c
          echo 'int main() { printf("Hello, World!\\n"); return 0; }' >> hello.c
          gcc -static -o hello.exe hello.c

      - name: Verify Executable
        shell: pwsh
        run: .\hello.exe