name: Build and Install MinGW-w64 from Source on Windows

on: [push]

jobs:
  build-mingw64:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      shell: cmd
      run: |
        choco install -y make
        choco install -y git
        choco install -y wget
        choco install -y 7zip

    - name: Download and Extract MinGW-w64 source
      shell: bash
      run: |
        wget https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/mingw-w64-v10.0.0.tar.bz2
        7z x mingw-w64-v10.0.0.tar.bz2
        7z x mingw-w64-v10.0.0.tar

    - name: Configure MinGW-w64
      shell: bash
      run: |
        cd mingw-w64-v10.0.0
        ls -l
        chmod +x configure
        ./configure --prefix="$HOME/mingw64" --enable-static --disable-shared

    - name: Build MinGW-w64
      shell: bash
      run: |
        make -j$(nproc)

    - name: Install MinGW-w64
      shell: bash
      run: |
        make install

    - name: Add MinGW-w64 to PATH
      shell: bash
      run: |
        echo "$HOME/mingw64/bin" >> $GITHUB_PATH