name: Build Simple Static QT GUI Using MinGW-w64 and QT 6.5.3

on: [push]

jobs:
  build-qt-gui:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      shell: cmd
      run: |
        choco install -y make
        choco install -y git
        choco install -y wget
        choco install -y 7zip
        choco install -y mingw
        choco install -y qt --version=6.5.3

    - name: Set up QT environment
      shell: bash
      run: |
        echo "C:\Qt\6.5.3\mingw81_64\bin" >> $GITHUB_PATH

    - name: Build a simple QT GUI
      shell: bash
      run: |
        echo '#include <QApplication>' > main.cpp
        echo '#include <QLabel>' >> main.cpp
        echo 'int main(int argc, char **argv) {' >> main.cpp
        echo 'QApplication app (argc, argv);' >> main.cpp
        echo 'QLabel label ("Hello, World!");' >> main.cpp
        echo 'label.show();' >> main.cpp
        echo 'return app.exec();' >> main.cpp
        echo '}' >> main.cpp
        g++ -o hello_qt main.cpp -I C:/Qt/6.5.3/mingw81_64/include -L C:/Qt/6.5.3/mingw81_64/lib -lQt6Widgets -lQt6Core -lQt6Gui -static
        ./hello_qt
